In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

In [2]:
df = pd.read_csv("../../data/customer.csv")

In [3]:
df.head(5)

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
df["review"].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [5]:
df["education"].value_counts()

education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [6]:
# Ordinal encoding will be applied to ordinal categorical features -- review and education
# Label encoding will be applied to categorical label -- purchased

In [7]:
df_ordinal_and_label = df.iloc[:, 2:]

In [8]:
X = df_ordinal_and_label.drop(columns=["purchased"])
y = df["purchased"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
X_train

     review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG
6      Good    School
41     Good        PG
46     Poor        PG
47     Good        PG
15     Poor        UG
9      Good        UG
16     Poor        UG
24  Average        PG
34  Average    School
31     Poor    School
0   Average    School
44  Average        UG
27     Poor        PG
33     Good        PG
5   Average    School
29  Average        UG
11     Good        UG
36     Good        UG
1      Poor        UG
21  Average        PG
2      Good        PG
43     Poor        PG
35     Poor    School
23     Good    School
40     Good    School
10     Good        UG
22     Poor        PG
18     Good    School
49     Good        UG
20  Average    School
7      Poor    School
42     Good        PG
14     Poor        PG
28     Poor    School
38     Good    School

In [10]:
y_train

12     No
4      No
37    Yes
8      No
3      No
6      No
41    Yes
46     No
47    Yes
15     No
9     Yes
16    Yes
24    Yes
34     No
31    Yes
0      No
44     No
27     No
33    Yes
5     Yes
29    Yes
11    Yes
36    Yes
1      No
21     No
2      No
43     No
35    Yes
23     No
40     No
10    Yes
22    Yes
18     No
49     No
20    Yes
7     Yes
42    Yes
14    Yes
28     No
38     No
Name: purchased, dtype: str

In [11]:
oe = OrdinalEncoder(categories=[["Poor", "Average", "Good"], ["School", "UG", "PG"]])
le = LabelEncoder()

In [12]:
X_train_oe = oe.fit_transform(X_train)
X_test_oe = oe.transform(X_test)

In [13]:
X_train_oe

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [14]:
y_train_le = le.fit_transform(y_train)
y_test_le = le.transform(y_test)

In [15]:
y_train_le #Label Encoding done

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [16]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [17]:
X_train_oe_df = pd.DataFrame(X_train_oe, columns=X_train.columns)
X_test_oe_df = pd.DataFrame(X_test_oe, columns=X_test.columns)

In [18]:
X_train_oe_df #Ordinal Encoding done

    review  education
0      0.0        0.0
1      1.0        1.0
2      1.0        2.0
3      1.0        1.0
4      2.0        2.0
5      2.0        0.0
6      2.0        2.0
7      0.0        2.0
8      2.0        2.0
9      0.0        1.0
10     2.0        1.0
11     0.0        1.0
12     1.0        2.0
13     1.0        0.0
14     0.0        0.0
15     1.0        0.0
16     1.0        1.0
17     0.0        2.0
18     2.0        2.0
19     1.0        0.0
20     1.0        1.0
21     2.0        1.0
22     2.0        1.0
23     0.0        1.0
24     1.0        2.0
25     2.0        2.0
26     0.0        2.0
27     0.0        0.0
28     2.0        0.0
29     2.0        0.0
30     2.0        1.0
31     0.0        2.0
32     2.0        0.0
33     2.0        1.0
34     1.0        0.0
35     0.0        0.0
36     2.0        2.0
37     0.0        2.0
38     0.0        0.0
39     2.0        0.0